### PR TITLE
310 make collect locations dynamic in footer

### PR DESCRIPTION
**Pull request by bveldkamp**
Some notes:

- I'm not sure if this is the best place for context_processors.py
- The addresses will now show the city, rather than the neighborhood (i.e. Vogelbuurt), if we want those too, they should probably be added to the address's description
- Depending on the length of the description, addresses may not be properly aligned

### CODE REVIEW

**Comment by mgvd** [comment]
The neighborhood is stored in the description field, the name field is used for the location name (i.e. Averechts, Krachtstation). Can you update the template to show both?

**Comment by bveldkamp** [comment]
Okay, I totally missed the name field, and will change it. 
Is city still necessary then, there aren't any plans to expand outside Utrecht, right?

**Comment by mgvd** [comment]
Agreed, City is not necessary, so we can leave that out.


Op wo 11 okt 2023 om 16:38 schreef Berend Veldkamp ***@***.***

**Comment by bveldkamp** [comment]
Fixed it. The address should now be exactly the same as it is on production

**Pull request merged**
